### ISSUE TITLE
[1.15.2] Mod failed to load correctly

### ISSUE THREAD

**Issue by usnavy2008** [MC-U-Team/GJEB-GammaJustExtremeBright#2]
**Describe the bug**
Upon putting the mod in mods folder (yes using forge 1.15.2 also with optifine) after starting the gaming up before getting to main menu. It tells me
"GJEB (GammaJustExtremeBright) (gjeb) has failed to load correctly
field_213107_d

**To Reproduce**
2. Do this '....'

**Expected behavior**

**Screenshots**

**Versions**
- Mod version: xxx
- Minecraft version: xxx
- Forge version: xxx
- UTeamCore version: xxx

**Log (if crash occures)**
Link to crash log

**Comment by HyCraftHD** [comment]
I mean optifine is not compatible with forge currently so thats the problem. Also the issue template is there to fill it out and not to leave everything open.
