### ISSUE TITLE
[1.19] This mod does not work with Optifine or Rubidium and has no GUI

### ISSUE THREAD

**Issue by Tsoccerguy3** [MC-U-Team/GJEB-GammaJustExtremeBright#25]
### Bug description and reproduction steps

I can not find any documentation for this mod 
No way to increase gamma in game except vanilla light level 1 to 100
not working with Optifine or Rubidium ( graphic optimizations )
it does not have any key binding 
No GUI that i can see .

### Log files and Screenshots

Nothing to post , the mod does nothing that i can see . No errors in logs 

### Used minecraft version

1.19.x

### Used forge version

forge-1.19-41.0.63-installer

### Used mod version

gjeb-1.19-1.1.3.19

**Comment by HyCraftHD** [comment]
Rubidium support was added in https://www.curseforge.com/minecraft/mc-mods/gjeb/files/3865565.
Optifine is currently unsupported as optifine builds are not stable yet.
