### ISSUE TITLE
Mod File gjeb-1.16.2-1.1.1.8.jar needs language provider javafml:33 or above to load

### ISSUE THREAD

**Issue by bertiespencer** [MC-U-Team/GJEB-GammaJustExtremeBright#3]
Mod File gjeb-1.16.2-1.1.1.8.jar needs language provider javafml:33 or above to load

**Comment by HyCraftHD** [comment]
Yes, it needs at least forge 33.0.0 to load? Where is the problem?

**Comment by bertiespencer** [comment]
Sorry my bad, I was using forge for 1.16.1 and I assumed it was backwards compatible.
